### ISSUE TITLE
Port to TTT2 HUD-System

### ISSUE THREAD

**Issue by TimGoll** [Exho1/TTT_Octagonal_HUD#7]
Since you do not have a license listed I have to ask about this: Am I allowed to fork your addon, port it to the new TTT2 HUD system and rerelease it on steam? (I suspect you aren't interested to port it by yourself)

**Comment by Exho1** [comment]
Be my guest!

**Comment by TimGoll** [comment]
I'll let you know once I've finished it :)

**Comment by TimGoll** [comment]
Feel free to follow the project here: https://github.com/TTT-2/ttt2-octagonal-hud

**Comment by TimGoll** [comment]
I started with it today and I'm quite happy with it! :)
It's written completely from scratch, but I try to follow your design language

![image](https://user-images.githubusercontent.com/13639408/60360680-8e412680-99dc-11e9-930a-cea17d888d1b.png)

**Comment by TimGoll** [comment]
In case you're interested: I've finished it!

![image](https://user-images.githubusercontent.com/13639408/60386647-50a1d380-9a98-11e9-9b84-33cd2f7503b7.png)
(Main HUD element and MStack)

![image](https://user-images.githubusercontent.com/13639408/60386649-55668780-9a98-11e9-86f8-34d08ad6374f.png)
(Other Elements)

![image](https://user-images.githubusercontent.com/13639408/60386690-d02fa280-9a98-11e9-8d4b-509dd70ca9eb.png)
(Supports TTT2 Classes as secondary role information)

![image](https://user-images.githubusercontent.com/13639408/60386653-60211c80-9a98-11e9-963b-352a73917980.png)
(TTT2 HUD Switcher)

![image](https://user-images.githubusercontent.com/13639408/60386657-6c0cde80-9a98-11e9-9d43-860f059669c8.png)
(Supports the scaling system of TTT2 HUDs)

**Comment by TimGoll** [comment]
Octagonal HUD got released, I'd really appreciate it if you'd link to this addon on your WS page. Thanks!

https://steamcommunity.com/sharedfiles/filedetails/?id=1795267605
